$ANSIBLE_VAULT;1.1;AES256
65383362633830323563666631363435643561373865356661306664353866646366343535316138
3535666235626336363630653431376237663435656438620a303735643936353366353937663937
62333938396539653637353731353837363365363363633739363665626263666465626261653336
3030616162636662370a643836306335356164323563383638666133366534313963303365396338
30653134663266323333373863393938616333623963383636346466393330396661356634343438
61633662616238336337616236613633633163323965343765303238343735303561643664623666
30636130656166656530363735396565373336303636396533393532646431653639326361663964
31626666323734303032383464303739353331326336356237313963643530356232636431313764
64336138363961313432306630656665323664396264666262323738373263323235343063303533
33316533303863633332383039313762386533346430303263313061616165663238343936383534
39373331646239336465363862356666396163636563633733393334343662663137653866636331
66626233333665393736
