$ANSIBLE_VAULT;1.1;AES256
61623638366234346166643237323438323331343531373932356431373363303739636266666464
3533626230616431613338646664653234356231666666660a636235366639643634663730666333
39353632393330653166323433666465663839363630303435346236633766323065396331373430
6438663239646435360a386231356235613936623564383835616333396261343538666233353130
35303562653763366436356335343436386266313137633564393231636266303838383832326162
62316666663535306633633731373361376262373032333638393466373638623434333938363462
30383238323035633934356264343231383536396638383061656538663630363037363139613137
37373761306533656533376662316237316465373631393863373033346237383634393430643133
33363833383135646463323131353038656331333435363464366536643430653465396532333432
39643932313263666239353434346333653266343231383239346634313262646134313137373030
33346232353264653531616533363262636334613234626137386461653231336635363565643035
38373131653332333964336533666539396530363864393635353132653662356663303566353436
30303563656565383639306636666161366266376431656137373139396239383365666138313634
32656337653962346665663861613538383332623564396164366563656232393332393532623433
36356333343730353936316330636337623031346665653138363130363638336562353361343264
39336439656132393533656561616239393930643535636439326266306462623163316333646362
35383333393937613233326330323138353236656336643930383964303131633134613439653632
6538653234393462623061383833663761356131653533633365
