$ANSIBLE_VAULT;1.1;AES256
35633334303764633463626130383461613633656164376365623161343630396430383936656335
6134623531363038636530666236633964366435306136370a666431323937386430636337343539
38653638343834653661633733316330623432323063333564643430363364316364393166643665
3637316266363232380a333639323236306134633831356336376266326434666465313136663932
34306565373633333633613862343066303439336330323138343834363430643561663534313266
65616465383437373562363535303034356238336434613662663665633363653837303630653863
33383363316637313438356530376239386366383939623366633637643565316161383635313930
33656230643564663466626465383736386235666462336665323730633235323065393237376264
30623237393163326666353835646538616633313432643461643530346165363032366162396363
66396462323339343830326339316339333138633330396436373931363830316435386330633336
38393537643265616336626231336538663733633563646239373261303666363535613932323732
63623135376132333336383636623462313831383965623039613861393231376131323166323864
30636362333039333631343733393739623763336166356131376338373035333434363562626238
62616135396665363562366538333535656366663431643033346630396633373738383965623231
36643364633033373730313562333631383436656162316533316165653431326539366266616139
63313333353130336538343833336365626338633161653863636464363162633138326237616437
38303433346663333337393530646339663263373238653861303963333066366436356334313365
3864643235346133666636636533343865663861356266313231
