$ANSIBLE_VAULT;1.1;AES256
37303830633165343236303134353264363830303065636536663731386236356633333533393938
3038333136613262643936393235353563383135386435300a373636616266303363616262386666
36353537613063383261396631623632336561343065643263383964386236323636356135666562
3231336634353332360a653031393231393231396561383333653330646366666364363933323761
61666362663734363166343436313337386131323666333632356236663237656336633837343363
63373961323261663530363336616633356636633239396661396665663037656664393064333763
66633736626133333733663063623766343435396365373134353834383063383230323862663032
32646638333766323532383464313661303965316238333431316564346538613966306435636237
30306633663839313236666366666265323439626638626363336634376230366331643861306330
35376334356138653466353036323261353965316330386662616364303239653739323831396664
33656533323362633861313830623339353866333130356137363639323035643031356463653064
64396561626563353638306638316563623466633065393631303637646466616531383164653330
39366130613666373966616364393866396430643162643638363832323237383037653734653762
61623262366562343965386664663966353431303664656664636164363539643430373833333764
33303863383131613362336239636430346130666664653262303765326166303139643364376563
64636530326331333533663336393663353963313463306664643163313865616562313236333735
64323461616465313137356164656165316436653962646339393934396165633434646134613033
3835313733363362333965623062303435326665366361653966
